### PR TITLE
Fix SponsorBlock zero videoDuration bug

### PR DESCRIPTION
**Pull request by iBicha**
Fixes a bug where SponsorBlock reports that the video has a duration of zero.

Reported from Reddit https://www.reddit.com/r/selfhosted/comments/zb07p0/comment/iyq52av/?utm_source=share&utm_medium=web2x&context=3

### CODE REVIEW

**Comment by iBicha** [comment]
Although the current fix is to skip segments with `videoDuration` = 0, the official SponsorBlock extension does not skip it.
Will change the approach to use the actual video duration instead.

**Comment by iBicha** [comment]
Added a follow up task to this in the roadmap, this fix should do for now

**Comment by mchangrh** [comment]
VideoDuration is not checked locally since it has been unreliable, as you have witnessed first hand. Segments are displayed regardless and if there's a detected duration mismatch when it's checked, the server will hide segments and not send them to any clients.

**Comment by iBicha** [comment]
> VideoDuration is not checked locally since it has been unreliable, as you have witnessed first hand. Segments are displayed regardless and if there's a detected duration mismatch when it's checked, the server will hide segments and not send them to any clients.

@mchangrh from the docs
>    videoDuration: float // Duration of video when submission occurred (to be used to determine when a submission is out of date). 0 when unknown. +- 1 second

Should I ignore the videoDuration field entirely?

**Pull request merged**
